### ISSUE TITLE
Wireguard

### ISSUE THREAD

**Issue by xbc5** [robur-coop/qubes-miragevpn#6]
This might be a bit cheeky of me, but is it possible to lay the groundwork for future Wireguard support?

I'm thinking it may save a major refactor in the future; or is support fixed on the OpenVPN protocol?

**Comment by dinosaure** [comment]
At present, the unikernel only supports OpenVPN. As far as Wireguard is concerned, we need an OCaml implementation of this protocol. We've discussed such support internally, and it's clearly a good idea, but we haven't yet found the time to embark on such a goal for the time being.
