### ISSUE TITLE
Share code between qubes-mirage-firewall and qubes-miragevpn in a separate repository

### ISSUE THREAD

**Issue by hannesm** [robur-coop/qubes-miragevpn#9]
This should lead to more shared code and less required maintenance. It is not really clear what the API should be, but we should strive towards the goal of more shared code :)

This repository as an advantage over qubes-mirage-firewall doesn't use any OCaml objects, and thus is easier to understand.

**Comment by palainp** [comment]
I totally agree with that, and this will possibly open a path for more virtual network functions. If we're only considering network  functions running in Qubes, maybe it can be added to mirage-qubes? I neither have clear idea what shape the API should take.

**Comment by hannesm** [comment]
Let's get into more detail in https://github.com/mirage/mirage-qubes/issues/70
